### PR TITLE
fix: add default field to exports in package.json for better compatibility

### LINKED ISSUE #390: v3.0.0 + TypeScript Cannot find module 'redux-actions' from ...
The new ESM version fails to be imported by TypeScript.

Here's a reproducible comparison:

- v2.6.5: https://replit.com/@kaelig/ReduxActionsV2BugReport#index.ts
- v3.0.0: https://replit.com/@kaelig/ReduxActionsV3BugReportTS#index.ts

In the shell, run:

```console
tsc index.ts
```

- v2.6.5: compiles successfully
- v3.0.0:

```
~/ReduxActionsV3BugReportTS$ tsc index.ts
index.ts:1:30 - error TS2307: Cannot find module 'redux-actions' or its corresponding type declarations.

1 import { createAction } from 'redux-actions';
                               ~~~~~~~~~~~~~~~

Found 1 error in index.ts:1
```

Screenshot 2023-03-02 at 10 07 05 AM

### LINKED ISSUE #399: Not working with `Jest` from v3.0.0
When upgrading to `3.0.0`, `Jest`is unable to find the redux-actions package:

```
● Test suite failed to run

    Cannot find module 'redux-actions' from '.../XXX.ts'

    Require stack:
    ...
    > 1 | import { handleActions } from 'redux-actions';
```

My project is built by `webpack`, so I cannot migrate it to `ESM`, but everything else works with v3 - `typescript` compilation, `webpack` dev server runs perfectly working application and `webpack build` runs without any errors.

_Addition information:_
The dependency is added together with `@types/redux-actions`, it is included in each package's `package.json`, but I also added it to the root one, from where the tests are run
```
Node v16
npm v8
yarn v1
```

### PR DESCRIPTION
**Pull request by Thiry1**
Add default field to exports in package.json for better compatibility.
Jest will be able to load the module and execute the transform.
fix #399
fix #390

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -18,7 +18,8 @@
   "module": "./dist/redux-actions.js",
   "exports": {
     ".": {
-      "import": "./dist/redux-actions.js"
+      "import": "./dist/redux-actions.js",
+      "default": "./dist/redux-actions.js"
     }
```
Comment (kei-sakamoto-dwango) [inline package.json:23]: Alternatively, the following configuration also worked well
```json
{
  "exports": "./dist/redux-actions.js"
}
```

File: package.json [hunk 2]
```diff
@@ -18,7 +18,8 @@
...
   },
```
Comment (Thiry1) [inline package.json:24]: Alternatively, the following configuration also worked well
```json
{
  "exports": "./dist/redux-actions.js"
}
```

**Comment by Thiry1** [comment]
@alexander-heimbuch  Could you please take a moment to review it?

**Comment by kaelig** [comment]
Thank you! 👍🏻

**Comment by Thiry1** [comment]
@alexander-heimbuch Thank you for merging. If possible, could you also publish it?

**Comment by alexander-heimbuch** [comment]
Later today :)

**Comment by alexander-heimbuch** [comment]
Fix is released in 3.03

**Comment by Thiry1** [comment]
Thank you!
